[[Overseers]]
ID="Overseers1"
[Overseers.TranningPlan]
PlanConfig1="config1"
[Overseers.TranningPlan.Map]
MapValue1="MapValue1"
[[Overseers]]
ID="Overeeers2"
[Overseers.TranningPlan]
PlanConfig2="config2"
[Overseers.TranningPlan.Map]
MapValue2="MapValue2"
[[Workers]]
ID="Worker1"
[Workers.TranningPlan]
Type="exampleworker"
[Workers.TranningPlan.Config]
Value1="Value1"
Value2="Value2"
[[Workers]]
ID="Worker2"
[Workers.TranningPlan]
Type="exampleworker2"
[Workers.TranningPlan.Config]
Value3="Value3"
Value4="Value4"
