package tools

import (
	"text/template"
)

var Template = template.Must(template.New("main").Parse(`package {{.Name}}

//Auto generated code for hiring workers.
//DO NOT EDIT THIS FILE.
import worker "github.com/herb-go/worker"

func init(){
{{- $id := .ID}}
{{- range $key, $value := .Workers }}
	worker.Hire("{{$id}}.{{$value}}", &{{$value}})
{{- end }}
}`))
